/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
      data: {
        loading: "loading",
      },
    },
    extend: {
      colors: {
        background: {
          DEFAULT: "var(--color-bg)",
          transparent: "var(--color-bg-transparent)",
          hover: "color-mix(in srgb, var(--color-bg), black 5%)",
          active: "color-mix(in srgb, var(--color-bg), black 6%)",
          selected: "color-mix(in srgb, var(--color-bg), black 8%)",
          secondary: "var(--color-bg-secondary)",
          accent: "var(--ramp-blue-500)",
          "accent-hover": "color-mix(in srgb, var(--color-bg-accent), white 10%)",
          "accent-active": "color-mix(in srgb, var(--color-bg-accent), black 10%)",
          neutral: "var(--ramp-grey-100)",
          "neutral-hover": "color-mix(in srgb, var(--color-bg-neutral), black 5%)",
          "neutral-subtle": "color-mix(in srgb, var(--color-bg-neutral), white 5%)",
          "neutral-subtle-hover": "color-mix(in srgb, var(--color-bg-neutral-subtle), white 10%)",
          "neutral-subtle-active": "color-mix(in srgb, var(--color-bg-neutral-subtle), black 5%)",
          "neutral-strong": "color-mix(in srgb, var(--color-bg-neutral), black 10%)",
          assistive: "var(--ramp-grey-900)",
          "assistive-transparent": "color-mix(in srgb, var(--color-bg-assistive), transparent)",
          negative: "var(--ramp-red-500)",
          "negative-subtle": "color-mix(in srgb, var(--color-bg-negative) 10%, white 90%)",
          easy: "var(--ramp-green-100)",
          medium: "var(--ramp-orange-100)",
          hard: "var(--ramp-red-100)",
          question: "var(--ramp-purple-100)",
          quiz: "var(--ramp-orange-100)",
        },
        foreground: {
          fg: "var(--ramp-grey-900)",
          subtle: "color-mix(in srgb, var(--color-fg) 70%, white 20%)",
          onaccent: "var(--ramp-white-1000)",
          accent: "var(--ramp-blue-500)",
          "accent-strong": "color-mix(in srgb, var(--color-fg-accent) black 20%)",
          neutral: "var(--ramp-grey-900)",
          "neutral-subtle": "var(--color-fg-neutral-subtle)",
          "neutral-subtle-hover": "var(--color-fg-neutral-subtle-hover)",
          "on-assistive": "var(--ramp-white-1000)",
          negative: "var(--ramp-red-500)",
          easy: "var(--ramp-green-900)",
          medium: "var(--ramp-orange-900)",
          hard: "var(--ramp-red-900)",
          question: "var(--ramp-purple-900)",
          quiz: "var(--ramp-orange-900)",
        },
        border: {
          DEFAULT: "var(--color-border)",
        },
        social: {
          github: "#333",
          twitter: "#1DA1F2",
          facebook: "#4267B2",
          linkedin: "#0077B5",
          reddit: "#FF4500",
          discord: "#7289DA",
        },
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          "0%": { transform: "scale(0.95)", opacity: 0 },
          "100%": { transform: "scale(1)", opacity: 1 },
        },
        "fade-out": {
          "0%": { transform: "scale(1)", opacity: 1 },
          "100%": { transform: "scale(0.95)", opacity: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s both",
        "fade-out": "fade-out 0.3s both",
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("tailwindcss-animate")],
};
