name: Index Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  start:
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      NEXT_BASE_URL: ${{ secrets.NEXT_BASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm i
      - run: npm run readme
      - uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update index"
